USE Library
GO

BEGIN TRANSACTION trans2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED --设置为读未提交
SELECT * FROM Book WHERE Bno = 'B01'
WAITFOR DELAY '00:00:10';
SELECT * FROM Book WHERE Bno = 'B01' 
COMMIT TRANSACTION;
